### ISSUE TITLE
Brainstorming de ideas.

### ISSUE THREAD

**Issue by albertbry9** [LeoAlfaroC/concurrente#4]
3 propuestas obtenidas.

**Comment by LeoAlfaroC** [comment]
Las tres ideas son:
- Aplicación móvil para programación de citas médicas en cualquiera de los hospitales o clínicas registrados en el sistema. El componente de blockchain se usaría para el almacenamiento de las citas.
- Aplicación de identificación de personas para búsqueda de antecedentes penales. El componente de aprendizaje de máquina se usaría para la identificación de personas a partir de una fotografía del rostro. El componente de blockchain se usaría para el almacenamiento de antecedentes penales.
- Aplicación de identificación de placas de vehículos para búsqueda de historial de papeletas y registro de nuevas multas. El componente de aprendizaje de máquina se usaría para la identificación de placas a partir de una fotografía de un vehículo detenido. El componente de blockchain se usaría para el almacenamiento de papeletas.
